- name: install redis
  apt: name=redis-server

- name: set service file
  template:
    src: redis.service.j2
    dest: /lib/systemd/system/redis-server.service
  notify:
    Reload service redis, in all cases

- name: set config file
  template:
    src: redis.conf.j2
    dest: "{{redis_config_file}}"
  notify:
    restart redis 


  