---
- debug: var=ansible_all_ipv4_addresses
- debug: var=ansible_default_ipv4.address
- debug: var=ansible_host
- name: create group elk
  group:
    name: "{{elk_group}}"
    state: present

- name: create user elk
  user:
    name: "{{elk_username}}"
    group: "{{elk_group}}"
    state: present 

- name: Extract logstash
  unarchive:
    src: logstash-7.7.0.tar.gz
    dest: /opt/
    list_files: yes
    owner: "{{elk_username}}"
    group: "{{elk_group}}"
  register: archive_logstash

- set_fact: logstash_dir="{{('/opt', 'logstash-' + logstash_version) | path_join}}" 

- name: install logstash service
  template:
    src: logstash.service.j2
    dest: "{{systemd_dir}}/logstash.service"

- name: copy config file
  template:
    src: mysql_slow.conf
    dest: "{{logstash_dir}}/config/mysql.conf"

- name: systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart logstash
  service:
    state: restarted
    name: logstash
  