- name: Create OpenLDAP dbconf
  template: >
    src=debconf-slapd.j2
    dest=/root/debconf-slapd.conf
    owner=root
    group=root
    mode=0644
  tags: first

- name: debconf-set-selections
  shell: "cat /root/debconf-slapd.conf | debconf-set-selections"
  environment: "{{ env }}"
  tags: openldap

- name: Install OpenLDAP packages
  apt: name={{ openldap_packages }} state=present update_cache=yes
  environment: "{{ env }}"
  tags: openldap