- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart zookeeper
  service:
    name=zookeeper
    state=restarted

- name: restart kafka
  service:
    name=kafka
    state=restarted