---

- name: create group elk
  group:
    name: "{{elk_group}}"
    state: present

- name: create user elk
  user:
    name: "{{elk_username}}"
    group: "{{elk_group}}"
    state: present 

- name: create kafka dir
  file:
    path: /opt/kafka
    state: directory 

- name: Extract kafka.tar.gz
  unarchive:
    src: kafka_2.11-2.2.0.tar.gz 
    dest: /opt/kafka
    list_files: yes
    owner: "{{elk_username}}"
    group: "{{elk_group}}"
    extra_opts: [--strip-components=2]
  register: archive_kafka


- name: set kafka server config
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties
      
- name: install kafka service
  template:
    src: kafka.service.j2
    dest: "{{systemd_dir}}/kafka.service"

- name: install zookeeper service
  template:
    src: zookeeper.service.j2
    dest: "{{systemd_dir}}/zookeeper.service"


- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart zookeeper
  service:
    name=zookeeper
    state=restarted

- name: restart kafka
  service:
    name=kafka
    state=restarted