---

- name: Extract Kibana
  unarchive:
    src: kibana-7.6.1-linux-x86_64.tar.gz
    dest: /opt/
    list_files: yes
  register: archive_kibana

- set_fact: kibana_home="{{('/opt/', archive_kibana.files[0]) | path_join | dirname}}"

- debug: var=kibana_home


- name: set kibana config
  template:
    src: kibana.yml.j2
    dest: "{{kibana_home}}/config/kibana.yml"

- name: install service
  template:
    src: kibana.service.j2
    dest: "{{systemd_dir}}/kibana.service"

- name: change es dir's owner to elk
  file:
    path: "{{es_dir}}"
    owner: {{run_as_user}}
    group: {{run_as_group}}
    recurse: yes

- name: systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: start kibana
  service:
    state: restarted
    name: kibana